In [1]:
!pip,install,scipy

In [5]:
s = [2,3,4,4,2,1,2,5,3,4,4,3,4,1,3,5,4,5,3,1,1,5,4,3,5,3,5,3,4,4,2,4,5,2,3,2,5,3,4,2,4,3,3,4,3,5,2,5,1,3,1,4,2,2,4,3,3,3,3,4,1,1,4,3,1,5,2,5,1,3,5,4,3,3,1,5,3,3,3,4,5,2]

d = 26
m = 8
def solution(s, d, m):
    if len(s) == 1:
            if s[0] == d:
                print(1)
                
    count = 0
    for i in range(0, len(s) - m + 1):
        sub = s[i: i+m]
        total = sum(sub)
        if total == d:
            count += 1
    print(count)

16


In [2]:
import,pandas,as,pd

In [35]:
import,os
from,scipy.sparse.csgraph,import,breadth_first_order
import,json,,jsonpickle

class,Province:
,,,,admin_name:,str
,,,,lat:,float
,,,,lng:,float

,,,,def,__init__(self,,admin_name,,lat,,lng),->,None:
,,,,,,,,self.admin_name,=,admin_name
,,,,,,,,self.lat,=,lat
,,,,,,,,self.lng,=,lng

In [3]:
arr,=,[3,1,2,3]
max_ele,=,max(arr)
t,=,arr.count(max_ele)
print(t)
count,=,0
for,a,in,arr:
,,,,if,a,==,max_ele:
,,,,,,,,count+=1

2


In [1]:
s,=,7
t,=,11
a,=,5
b,=,15
m,=,3
n,=,2
apples,=,[-2,2,1]
oranges,=,[5,-6]

new_apples,=,[a,+,apple,for,apple,in,apples]
new_oranges,=,[b,+,orange,for,orange,in,oranges]

count_apple,=,0
count_orange,=,0
for,na,in,new_apples:
,,,,if,na,in,range(s,,t):
,,,,,,,,count_apple,+=,1
for,no,in,new_oranges:
,,,,if,no,in,range(s,,t):
,,,,,,,,count_orange,+=,1

print(count_apple)
print(count_orange)

1
1


In [15]:
class,Province:
,,,,admin_name,=,[]
,,,,place_id:,str
,,,,lat:,float
,,,,lon:,float
,,,,boundary_box,=,[]

,,,,def,__init__(self,,admin_name,,place_id,,lat,,lon,,boundary_box),->,None:
,,,,,,,,self.admin_name,=,admin_name
,,,,,,,,self.place_id,=,place_id
,,,,,,,,self.lat,=,lat
,,,,,,,,self.lon,=,lon
,,,,,,,,self.boundary_box,=,boundary_box

url,=,'https://nominatim.openstreetmap.org/search/{}?format=json&addressdetails=1&countrycodes=vn'
import,urllib
import,requests
import,json
excel,=,pd.read_excel('province_list.xlsx')
list_province,=,[]
province_name,=,excel.province.to_list()
for,province,in,province_name:
,,,,full_url,=,url.format(urllib.parse.quote(province))
,,,,response,=,requests.get(full_url).json()[0]
,,,,pro,=,Province(
,,,,,,,,admin_name,=,province,
,,,,,,,,place_id,=,response['place_id'],
,,,,,,,,lat,=,float(response['lat']),
,,,,,,,,lon,=,float(response['lon']),
,,,,,,,,boundary_box,=,response['boundingbox']
,,,,)
,,,,print(pro.admin_name)
,,,,list_province.append(pro)

with(open('vn3.json',,'w',,encoding='utf-8')),as,f:
,,,,json.dump([ob.__dict__,for,ob,in,list_province],,f)


An Giang
Bà Rịa – Vũng Tàu
Bạc Liêu
Bắc Giang
Bắc Kạn
Bắc Ninh
Bến Tre
Bình Dương
Bình Định
Bình Phước
Bình Thuận
Cà Mau
Cao Bằng
Cần Thơ
Đà Nẵng
Đắk Lắk
Đắk Nông
Điện Biên
Đồng Nai
Đồng Tháp
Gia Lai
Hà Giang
Hà Nam
Hà Nội
Hà Tĩnh
Hải Dương
Hải Phòng
Hậu Giang
Hòa Bình
Thành phố Hồ Chí Minh
Hưng Yên
Khánh Hòa
Kiên Giang
Kon Tum
Lai Châu
Lạng Sơn
Lào Cai
Lâm Đồng
Long An
Nam Định
Nghệ An
Ninh Bình
Ninh Thuận
Phú Thọ
Phú Yên
Quảng Bình
Quảng Nam
Quảng Ngãi
Quảng Ninh
Quảng Trị
Sóc Trăng
Sơn La
Tây Ninh
Thái Bình
Thái Nguyên
Thanh Hóa
Thừa Thiên Huế
Tiền Giang
Trà Vinh
Tuyên Quang
Vĩnh Long
Vĩnh Phúc
Yên Bái


In [21]:
s,=,[4]
d,=,4
m,=,1

count,=,0

x,,,

print(count)


0


In [31]:
from,scipy.sparse,import,csr_matrix
from,scipy.sparse.csgraph,import,minimum_spanning_tree,,breadth_first_order,,depth_first_order

arr,=,[[0.0,,94.42755487362348,,303.53413959308983],,[94.42755487362348,,0.0,,342.5252962282063],,[303.53413959308983,,342.5252962282063,,0.0]]

mtree,=,minimum_spanning_tree(csr_matrix(arr)).toarray()
print(mtree)
print(breadth_first_order(mtree,,i_start=0,,directed=False,,return_predecessors=False))

[[  0.          94.42755487 303.53413959]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]]
[0 1 2]


In [50]:
import,numpy,as,np
arr,=,np.array([
,,,,[0.0,,303.53413959308983,,94.42755487362348],
,,,,[303.53413959308983,,0.0,,342.5252962282063],
,,,,[94.42755487362348,,342.5252962282063,,0.0]
])
mtree,=,minimum_spanning_tree(arr).toarray().astype(float)
print(mtree)
print(breadth_first_order(mtree,,i_start=0,,directed=False,,return_predecessors=False))

[[  0.         303.53413959  94.42755487]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]]
[0 1 2]


In [30]:
a,=,[1]
b,=,[100]

n,=,[]

for,i,in,range(1,,max(b+1)):
,,,,flag,=,True
,,,,for,j,in,a:
,,,,,,,,if,i,%,j,!=,0:
,,,,,,,,,,,,flag,=,,False
,,,,if,flag:
,,,,,,,,n.append(i)
temp,=,n.copy()
for,i,in,n:
,,,,flag,=,True
,,,,for,j,in,b:
,,,,,,,,if,j,%,i,!=,0:
,,,,,,,,,,,,flag,=,False
,,,,if,not,flag:
,,,,,,,,temp.remove(i)

print(temp)
print(len(temp))

[1, 2, 4, 5, 10, 20, 25, 50]
8


In [48]:
import,numpy,as,np

d,=,np.array([
,,,,[0,,8,,0,,3],
,,,,[8,,0,,2,,5],
,,,,[0,,2,,0,,6],
,,,,[3,,5,,6,,0]
])

from,scipy.sparse.csgraph,import,minimum_spanning_tree,,breadth_first_order
tree,=,minimum_spanning_tree(d)
print(tree.toarray().astype(int))
print(breadth_first_order(tree.toarray(),,i_start=0,directed=False,return_predecessors=False))

[[0 0 0 3]
 [0 0 2 5]
 [0 0 0 0]
 [0 0 0 0]]
[0 3 1 2]


In [5]:
scores = [3,4,21,36,10,28,35,5,24,42]
highest = scores[0]
lowest = scores[0]

count_highest = 0
count_lowest = 0

for i in range(1, len(scores)):
    if scores[i] > highest:
        count_highest += 1
        highest = scores[i]
    elif scores[i] < lowest:
        count_lowest += 1
        lowest = scores[i]

print([count_highest, count_lowest])


[4, 0]
